name: delivery_boy
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+8

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  get: ^4.6.5
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.3.0
  google_maps_flutter: ^2.2.1
  geocode: ^1.0.2
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  connectivity_plus: ^3.0.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.7
  bot_toast: ^4.0.3
  location: ^4.4.0
  flutter_google_places: ^0.3.0
  flutter_polyline_points: ^1.0.0
  firebase_messaging: ^14.1.4
  firebase_core: ^2.4.0
  flutter_screenutil: ^5.3.1
  google_place: ^0.4.7
  vibration: ^1.7.6
  shimmer: ^2.0.0
  intl: ^0.17.0
  skeleton_text: ^3.0.0
  awesome_notifications: 0.7.4+1
  sunmi_printer_plus: ^2.1.1
  esc_pos_utils: ^1.1.0
  onesignal_flutter: ^3.5.0
  lottie: ^2.0.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  fonts:
   - family: Cairo
     fonts:
       - asset: assets/fonts/Cairo-Regular.ttf

  
  assets:
    - assets/svg/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/lottie/
    

  
